import numpy as np
import matplotlib.pyplot as plt
import pylab as pylab

# Plot ReLU function
x = np.linspace(-4, 4, 800)
plt.figure(figsize=(8, 8))
plt.plot(x, np.maximum(0, x), label="ReLU", color='b')
#plt.title("Activation Function")
#plt.xlabel("Input")
#plt.ylabel("Output")
plt.grid(True)
plt.axhline(0, color='black', linewidth=1)
plt.axvline(0, color='black', linewidth=1)
plt.legend()
#plt.show()
pylab.savefig('B-relu.png')
pylab.clf()

# Plot sigmoid function
x = np.linspace(-10, 10, 2000)
plt.figure(figsize=(8, 8))
plt.plot(x, 1 / (1 + np.exp(-x)), label="sigmoid", color='b')
#plt.title("Activation Function")
#plt.xlabel("Input")
#plt.ylabel("Output")
plt.grid(True)
plt.axhline(0, color='black', linewidth=1)
plt.axvline(0, color='black', linewidth=1)
plt.legend()
#plt.show()
pylab.savefig('B-sigmoid.png')
pylab.clf()

# Plot tanh function
x = np.linspace(-10, 10, 2000)
plt.figure(figsize=(8, 8))
plt.plot(x, np.tanh(x), label="tanh", color='b')
#plt.title("Activation Function")
#plt.xlabel("Input")
#plt.ylabel("Output")
plt.grid(True)
plt.axhline(0, color='black', linewidth=1)
plt.axvline(0, color='black', linewidth=1)
plt.legend()
#plt.show()
pylab.savefig('B-tanh.png')
pylab.clf()

# Plot custom activation function
x = np.linspace(-40, 40, 8000)
plt.figure(figsize=(8, 8))
plt.plot(x, -0.9 / (1 + np.exp(x / 5)) + 0.8 / (1 + np.exp(-x / 5)), label="custom", color='b')
#plt.title("Activation Function")
#plt.xlabel("Input")
#plt.ylabel("Output")
plt.yticks(np.arange(-0.9, 0.85, 0.1))
plt.grid(True)
plt.axhline(0, color='black', linewidth=1)
plt.axvline(0, color='black', linewidth=1)
plt.legend()
#plt.show()
pylab.savefig('B-custom_activation.png')
pylab.clf()
