"""
Random Initial Data with Homogeneous Dirichlet Boundary Conditions

This example generates uniformly distributed random initial data on the
interior of a two-dimensional Cartesian grid. The boundary values are set
equal to zero so that the initial condition satisfies homogeneous Dirichlet
boundary conditions.

The interior values are sampled independently from

    U(-amplitude, amplitude).

Such nonsmooth random data are useful for comparison with smooth initial
data generated by a Poisson problem.
"""

import matplotlib.pyplot as plt
import numpy as np


# =============================================================================
# Parameters
# =============================================================================

M = 128
L = 1.0
AMPLITUDE = 0.02
SEED = 42


# =============================================================================
# Generate random initial data
# =============================================================================

def generate_random_initial_data(
    M=128,
    amplitude=0.02,
    seed=42,
):
    """
    Generate uniformly distributed random initial data.

    Independent values are sampled from

        U(-amplitude, amplitude)

    at the interior grid points. The boundary values are set equal to zero
    to impose homogeneous Dirichlet boundary conditions.

    Parameters
    ----------
    M : int
        Total number of grid points in each spatial direction,
        including boundary points.
    amplitude : float
        Maximum magnitude of the random interior values.
    seed : int
        Random seed used for reproducibility.

    Returns
    -------
    u0 : ndarray
        Array of shape (M, M) containing the initial data.
    """

    if M < 3:
        raise ValueError("M must be at least 3.")

    if amplitude <= 0.0:
        raise ValueError("amplitude must be positive.")

    rng = np.random.default_rng(seed)

    u0 = np.zeros(
        (M, M),
        dtype=np.float64,
    )

    u0[1:-1, 1:-1] = rng.uniform(
        -amplitude,
        amplitude,
        size=(M - 2, M - 2),
    )

    return u0


# =============================================================================
# Main program
# =============================================================================

def main():
    """Generate, verify, and display the random initial data."""

    u0 = generate_random_initial_data(
        M=M,
        amplitude=AMPLITUDE,
        seed=SEED,
    )

    print(f"Grid size: {u0.shape}")
    print(f"Minimum value: {u0.min():.6f}")
    print(f"Maximum value: {u0.max():.6f}")

    boundary_max = max(
        np.max(np.abs(u0[0, :])),
        np.max(np.abs(u0[-1, :])),
        np.max(np.abs(u0[:, 0])),
        np.max(np.abs(u0[:, -1])),
    )

    print(
        "Maximum absolute boundary value: "
        f"{boundary_max:.6e}"
    )

    # -------------------------------------------------------------------------
    # Plot
    # -------------------------------------------------------------------------

    fig, ax = plt.subplots(figsize=(6, 5))

    image = ax.imshow(
        u0,
        origin="lower",
        extent=[-L, L, -L, L],
        cmap="coolwarm",
        vmin=-AMPLITUDE,
        vmax=AMPLITUDE,
    )

    fig.colorbar(
        image,
        ax=ax,
        label="Amplitude",
    )

    ax.set_title("Uniform Random Initial Data")
    ax.set_xlabel("$x$")
    ax.set_ylabel("$y$")

    fig.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()