"""
Two-Dimensional Chafee--Infante Equation:
Eyre-Type Semi-Implicit Time Stepping

This script computes numerical solutions of the two-dimensional
Chafee--Infante equation

    u_t - gamma * Delta u + kappa * (u^3 - u) = 0

on the square domain

    Omega = [-L, L] x [-L, L],

subject to homogeneous Dirichlet boundary conditions

    u = 0 on boundary(Omega).

The time discretization uses an Eyre-type convex--concave splitting.
The diffusion term and cubic term are treated implicitly, while the
destabilizing linear term is treated explicitly. At each time step,
the resulting nonlinear system is solved by Newton's method on the
interior grid.

The initial condition is generated by solving the discrete Poisson problem

    -Delta_h u = f,

with a random source term f and homogeneous Dirichlet boundary conditions.
The resulting field is normalized to have prescribed maximum amplitude.

The computation records selected solution snapshots, the quadratic energy,
the discrete Lyapunov energy, and the minimum and maximum solution values.

Requirements
------------
numpy
scipy
matplotlib
"""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.sparse import diags, eye, kron
from scipy.sparse.linalg import spsolve


# =============================================================================
# Parameters
# =============================================================================

N_STEPS = 2000
DELTA_T = 0.001

L = 1.0
M = 128

GAMMA = 0.005
KAPPA = 4.7

SNAPSHOT_STRIDE = 100

INITIAL_AMPLITUDE = 0.02
RANDOM_SEED = 0

NEWTON_MAX_ITERS = 12
NEWTON_TOL = 1.0e-10

# Numerical tolerance used when checking discrete Lyapunov-energy decay.
LYAPUNOV_ATOL = 1.0e-10
LYAPUNOV_RTOL = 1.0e-10

IMAGE_DIR = Path("images")
DATA_DIR = Path("data")

IMAGE_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR.mkdir(parents=True, exist_ok=True)


# =============================================================================
# Grid
# =============================================================================

X = np.linspace(-L, L, M)
Y = np.linspace(-L, L, M)

HX = X[1] - X[0]
HY = Y[1] - Y[0]

CELL_AREA = HX * HY

# Number of interior grid points in one coordinate direction.
MI = M - 2

# Total number of interior unknowns.
N_INTERIOR = MI * MI


# =============================================================================
# Discrete operators
# =============================================================================

def build_dirichlet_laplacian_1d(n_points, mesh_size):
    """
    Construct the one-dimensional second-difference Laplacian.

    Homogeneous Dirichlet boundary values are imposed externally,
    so the matrix acts only on the interior unknowns.

    Parameters
    ----------
    n_points : int
        Number of interior grid points.
    mesh_size : float
        Spatial mesh width.

    Returns
    -------
    scipy.sparse.csr_matrix
        Sparse matrix approximating the second derivative.
    """

    main_diagonal = -2.0 * np.ones(n_points)
    off_diagonal = np.ones(n_points - 1)

    laplacian = diags(
        [off_diagonal, main_diagonal, off_diagonal],
        offsets=[-1, 0, 1],
        shape=(n_points, n_points),
        format="csr",
    )

    return laplacian / mesh_size**2


def build_dirichlet_laplacian_2d(total_grid_points, mesh_size):
    """
    Construct the two-dimensional Dirichlet Laplacian.

    The discrete operator is the Kronecker sum

        Delta_h = I kron T + T kron I,

    where T is the one-dimensional second-difference matrix.

    Parameters
    ----------
    total_grid_points : int
        Total number of grid points in each direction, including
        boundary points.
    mesh_size : float
        Spatial mesh width.

    Returns
    -------
    scipy.sparse.csr_matrix
        Sparse two-dimensional Laplacian acting on interior unknowns.
    """

    n_interior = total_grid_points - 2

    laplacian_1d = build_dirichlet_laplacian_1d(
        n_interior,
        mesh_size,
    )

    identity = eye(
        n_interior,
        format="csr",
    )

    laplacian_2d = (
        kron(identity, laplacian_1d, format="csr")
        + kron(laplacian_1d, identity, format="csr")
    )

    return laplacian_2d


LAPLACIAN = build_dirichlet_laplacian_2d(
    M,
    HX,
)

IDENTITY = eye(
    N_INTERIOR,
    format="csr",
)


# =============================================================================
# Initial condition
# =============================================================================

def smooth_poisson_initial_condition(
    laplacian,
    amplitude=INITIAL_AMPLITUDE,
    seed=RANDOM_SEED,
):
    r"""
    Generate smooth random initial data using a discrete Poisson problem.

    A random interior source f is generated and the problem

        -Delta_h u = f

    is solved on the interior grid with homogeneous Dirichlet boundary
    conditions.

    The resulting solution is normalized according to

        u <- amplitude * u / ||u||_infinity.

    Parameters
    ----------
    laplacian : scipy.sparse matrix
        Discrete Dirichlet Laplacian on the interior grid.
    amplitude : float
        Desired maximum absolute value of the initial condition.
    seed : int
        Seed used to generate the random source.

    Returns
    -------
    u : ndarray
        Array of shape (M, M) satisfying homogeneous Dirichlet
        boundary conditions.
    """

    if amplitude <= 0.0:
        raise ValueError("amplitude must be positive.")

    rng = np.random.default_rng(seed)

    source = rng.standard_normal(N_INTERIOR)

    u_interior = spsolve(
        -laplacian,
        source,
    )

    maximum = np.max(
        np.abs(u_interior)
    )

    if maximum == 0.0:
        raise RuntimeError(
            "The Poisson solution has zero magnitude "
            "and cannot be normalized."
        )

    u_interior *= amplitude / maximum

    u = np.zeros(
        (M, M),
        dtype=np.float64,
    )

    u[1:-1, 1:-1] = u_interior.reshape(
        MI,
        MI,
    )

    return u


# =============================================================================
# Energies and diagnostics
# =============================================================================

def quadratic_energy(u):
    r"""
    Compute the discrete quadratic energy

        E_2(u) = (1/2) integral_Omega u^2 dx.

    Rectangular quadrature is used.
    """

    return (
        0.5
        * CELL_AREA
        * np.sum(u**2)
    )


def lyapunov_energy(u):
    r"""
    Compute the discrete Chafee--Infante Lyapunov energy

        E(u)
        =
        integral_Omega [
            (gamma/2) |grad u|^2
            + kappa (u^4/4 - u^2/2)
        ] dx.

    Forward differences are used to approximate the spatial gradient.
    """

    ux = np.diff(
        u,
        axis=0,
    ) / HX

    uy = np.diff(
        u,
        axis=1,
    ) / HY

    gradient_term = (
        np.sum(ux**2)
        + np.sum(uy**2)
    )

    potential = (
        0.25 * u**4
        - 0.5 * u**2
    )

    energy = (
        0.5 * GAMMA * gradient_term
        + KAPPA * np.sum(potential)
    ) * CELL_AREA

    return energy


def solution_diagnostics(u):
    """
    Return the minimum and maximum values of the numerical solution.
    """

    return (
        np.min(u),
        np.max(u),
    )


# =============================================================================
# Eyre-type semi-implicit time step
# =============================================================================

def eyre_step(u_previous):
    r"""
    Advance the numerical solution by one Eyre-type time step.

    The Chafee--Infante equation is

        u_t
        - gamma Delta u
        + kappa (u^3 - u)
        = 0.

    The diffusion and cubic terms are treated implicitly while the
    destabilizing linear term is treated explicitly:

        u^{n+1}
        - delta_t gamma Delta u^{n+1}
        + delta_t kappa (u^{n+1})^3

        =
        u^n
        + delta_t kappa u^n.

    On the interior grid, define

        F(v)
        =
        v
        - delta_t gamma L v
        + delta_t kappa v^3
        - (1 + delta_t kappa) u^n.

    Newton's method is applied to solve

        F(v) = 0.

    Parameters
    ----------
    u_previous : ndarray
        Numerical solution at the previous time level.

    Returns
    -------
    u : ndarray
        Numerical solution at the new time level.
    iteration : int
        Number of Newton iterations used.
    residual_norm : float
        Final Euclidean norm of the nonlinear residual.
    """

    previous_interior = u_previous[
        1:-1,
        1:-1,
    ]

    rhs = (
        1.0
        + DELTA_T * KAPPA
    ) * previous_interior

    u_interior = previous_interior.copy()

    converged = False
    residual_norm = np.inf

    for iteration in range(
        1,
        NEWTON_MAX_ITERS + 1,
    ):

        u_flat = u_interior.ravel()

        residual = (
            u_flat
            - DELTA_T
            * GAMMA
            * (LAPLACIAN @ u_flat)
            + DELTA_T
            * KAPPA
            * u_flat**3
            - rhs.ravel()
        )

        residual_norm = np.linalg.norm(
            residual,
            ord=2,
        )

        if residual_norm < NEWTON_TOL:
            converged = True
            break

        jacobian_diagonal = (
            3.0
            * DELTA_T
            * KAPPA
            * u_flat**2
        )

        jacobian = (
            IDENTITY
            - DELTA_T
            * GAMMA
            * LAPLACIAN
            + diags(
                jacobian_diagonal,
                offsets=0,
                format="csr",
            )
        )

        correction = spsolve(
            jacobian,
            -residual,
        )

        u_interior = (
            u_flat + correction
        ).reshape(
            MI,
            MI,
        )

    if not converged:
        raise RuntimeError(
            "Newton iteration failed to converge after "
            f"{NEWTON_MAX_ITERS} iterations; "
            f"final residual norm = {residual_norm:.3e}."
        )

    u = np.zeros(
        (M, M),
        dtype=np.float64,
    )

    u[1:-1, 1:-1] = u_interior

    return (
        u,
        iteration,
        residual_norm,
    )


# =============================================================================
# Snapshot output
# =============================================================================

def save_snapshot(u, step):
    """
    Save a numerical solution snapshot as a PNG image.
    """

    fig, ax = plt.subplots(
        figsize=(6, 5)
    )

    image = ax.imshow(
        u,
        origin="lower",
        extent=[-L, L, -L, L],
        cmap="magma",
        interpolation="none",
    )

    fig.colorbar(
        image,
        ax=ax,
        label="$u(x,y,t)$",
    )

    ax.set_xlabel("$x$")
    ax.set_ylabel("$y$")
    ax.set_title(
        f"Chafee--Infante Solution, Step {step}"
    )

    fig.tight_layout()

    fig.savefig(
        IMAGE_DIR / f"phi{step:05d}.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)


# =============================================================================
# Diagnostic plots
# =============================================================================

def save_diagnostic_plots(
    times,
    quadratic_values,
    lyapunov_values,
    minimum_values,
    maximum_values,
):
    """
    Save the quadratic-energy, Lyapunov-energy, and extrema plots.
    """

    # -------------------------------------------------------------------------
    # Quadratic energy
    # -------------------------------------------------------------------------

    fig, ax = plt.subplots(
        figsize=(6, 4)
    )

    ax.plot(
        times,
        quadratic_values,
        linewidth=1.5,
    )

    ax.set_xlabel("Time")
    ax.set_ylabel(r"$E_2(u)$")
    ax.set_title("Quadratic Energy")
    ax.grid(
        True,
        linestyle="--",
        alpha=0.5,
    )

    fig.tight_layout()

    fig.savefig(
        DATA_DIR / "quadratic_energy.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)

    # -------------------------------------------------------------------------
    # Lyapunov energy
    # -------------------------------------------------------------------------

    fig, ax = plt.subplots(
        figsize=(6, 4)
    )

    ax.plot(
        times,
        lyapunov_values,
        linewidth=1.5,
    )

    ax.set_xlabel("Time")
    ax.set_ylabel(r"$E(u)$")
    ax.set_title("Discrete Lyapunov Energy")
    ax.grid(
        True,
        linestyle="--",
        alpha=0.5,
    )

    fig.tight_layout()

    fig.savefig(
        DATA_DIR / "lyapunov_energy.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)

    # -------------------------------------------------------------------------
    # Minimum and maximum
    # -------------------------------------------------------------------------

    fig, ax = plt.subplots(
        figsize=(6, 4)
    )

    ax.plot(
        times,
        maximum_values,
        linestyle="--",
        linewidth=1.5,
        label="Maximum",
    )

    ax.plot(
        times,
        minimum_values,
        linestyle=":",
        linewidth=1.5,
        label="Minimum",
    )

    ax.set_xlabel("Time")
    ax.set_ylabel("Solution value")
    ax.set_title("Minimum and Maximum Solution Values")
    ax.legend()

    ax.grid(
        True,
        linestyle="--",
        alpha=0.5,
    )

    fig.tight_layout()

    fig.savefig(
        DATA_DIR / "solution_extrema.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)


# =============================================================================
# Main computation
# =============================================================================

def main():
    """
    Run the two-dimensional Chafee--Infante simulation.
    """

    print(
        "Two-dimensional Chafee--Infante equation"
    )

    print(
        "------------------------------------------"
    )

    print(f"Grid:          {M} x {M}")

    print(
        f"Domain:        "
        f"[-{L}, {L}] x [-{L}, {L}]"
    )

    print(
        f"Mesh size:     {HX:.6e}"
    )

    print(
        f"Time steps:    {N_STEPS}"
    )

    print(
        f"Time step:     {DELTA_T:.6e}"
    )

    print(
        f"Final time:    "
        f"{N_STEPS * DELTA_T:.6f}"
    )

    print(
        f"gamma:         {GAMMA:.6e}"
    )

    print(
        f"kappa:         {KAPPA:.6f}"
    )

    print()

    # -------------------------------------------------------------------------
    # Initial data
    # -------------------------------------------------------------------------

    initial_data_path = (
        DATA_DIR / "initial_data.csv"
    )

    if initial_data_path.exists():

        print(
            "Loading existing initial condition..."
        )

        u = np.loadtxt(
            initial_data_path,
            delimiter=",",
            dtype=np.float64,
        )

    else:

        print(
            "Generating smooth Poisson initial condition..."
        )

        u = smooth_poisson_initial_condition(
            LAPLACIAN
        )

        np.savetxt(
            initial_data_path,
            u,
            delimiter=",",
        )

        print(
            "Initial condition saved to "
            f"{initial_data_path}"
        )

    if u.shape != (M, M):

        raise ValueError(
            f"Initial condition has shape {u.shape}; "
            f"expected {(M, M)}."
        )

    # Verify the homogeneous Dirichlet boundary condition.
    boundary_max = max(
        np.max(np.abs(u[0, :])),
        np.max(np.abs(u[-1, :])),
        np.max(np.abs(u[:, 0])),
        np.max(np.abs(u[:, -1])),
    )

    if boundary_max > 1.0e-14:

        raise ValueError(
            "Initial condition does not satisfy the "
            "homogeneous Dirichlet boundary condition."
        )

    # -------------------------------------------------------------------------
    # Diagnostic storage
    # -------------------------------------------------------------------------

    times = np.empty(
        N_STEPS + 1,
        dtype=np.float64,
    )

    quadratic_values = np.empty(
        N_STEPS + 1,
        dtype=np.float64,
    )

    lyapunov_values = np.empty(
        N_STEPS + 1,
        dtype=np.float64,
    )

    minimum_values = np.empty(
        N_STEPS + 1,
        dtype=np.float64,
    )

    maximum_values = np.empty(
        N_STEPS + 1,
        dtype=np.float64,
    )

    times[0] = 0.0

    quadratic_values[0] = (
        quadratic_energy(u)
    )

    lyapunov_values[0] = (
        lyapunov_energy(u)
    )

    (
        minimum_values[0],
        maximum_values[0],
    ) = solution_diagnostics(u)

    save_snapshot(
        u,
        step=0,
    )

    print(
        "Initial minimum / maximum: "
        f"{minimum_values[0]:.6f}, "
        f"{maximum_values[0]:.6f}"
    )

    print(
        "Initial energies: "
        f"E2 = {quadratic_values[0]:.10e}, "
        f"Lyapunov = {lyapunov_values[0]:.10e}"
    )

    # -------------------------------------------------------------------------
    # Time stepping
    # -------------------------------------------------------------------------

    completed_steps = N_STEPS

    for step in range(
        1,
        N_STEPS + 1,
    ):

        (
            u,
            newton_iterations,
            residual_norm,
        ) = eyre_step(u)

        times[step] = (
            step * DELTA_T
        )

        quadratic_values[step] = (
            quadratic_energy(u)
        )

        lyapunov_values[step] = (
            lyapunov_energy(u)
        )

        (
            minimum_values[step],
            maximum_values[step],
        ) = solution_diagnostics(u)

        # ---------------------------------------------------------------------
        # Check discrete energy decay
        # ---------------------------------------------------------------------

        energy_increase = (
            lyapunov_values[step]
            - lyapunov_values[step - 1]
        )

        energy_tolerance = (
            LYAPUNOV_ATOL
            + LYAPUNOV_RTOL
            * abs(
                lyapunov_values[step - 1]
            )
        )

        if energy_increase > energy_tolerance:

            print()

            print(
                "Discrete Lyapunov energy increased "
                "beyond the numerical tolerance."
            )

            print(
                f"Previous energy: "
                f"{lyapunov_values[step - 1]:.12e}"
            )

            print(
                f"Current energy:  "
                f"{lyapunov_values[step]:.12e}"
            )

            print(
                f"Increase:        "
                f"{energy_increase:.12e}"
            )

            print(
                f"Tolerance:       "
                f"{energy_tolerance:.12e}"
            )

            print(
                "Terminating the simulation."
            )

            completed_steps = step
            break

        # ---------------------------------------------------------------------
        # Save selected snapshots
        # ---------------------------------------------------------------------

        if step % SNAPSHOT_STRIDE == 0:

            save_snapshot(
                u,
                step,
            )

            print(
                f"Step {step:5d}/{N_STEPS} | "
                f"min = {minimum_values[step]: .6f}, "
                f"max = {maximum_values[step]: .6f} | "
                f"E2 = {quadratic_values[step]:.10e}, "
                f"Ly = {lyapunov_values[step]:.10e} | "
                f"Newton = {newton_iterations:2d} | "
                f"residual = {residual_norm:.3e}"
            )

    # -------------------------------------------------------------------------
    # Trim diagnostic arrays if the simulation terminated early
    # -------------------------------------------------------------------------

    times = times[
        : completed_steps + 1
    ]

    quadratic_values = quadratic_values[
        : completed_steps + 1
    ]

    lyapunov_values = lyapunov_values[
        : completed_steps + 1
    ]

    minimum_values = minimum_values[
        : completed_steps + 1
    ]

    maximum_values = maximum_values[
        : completed_steps + 1
    ]

    # -------------------------------------------------------------------------
    # Save final numerical state
    # -------------------------------------------------------------------------

    np.savetxt(
        DATA_DIR / "final_solution.csv",
        u,
        delimiter=",",
    )

    # -------------------------------------------------------------------------
    # Save diagnostic figures
    # -------------------------------------------------------------------------

    save_diagnostic_plots(
        times,
        quadratic_values,
        lyapunov_values,
        minimum_values,
        maximum_values,
    )

    # -------------------------------------------------------------------------
    # Final report
    # -------------------------------------------------------------------------

    print()

    print(
        "Computation complete."
    )

    print(
        f"Final time reached: "
        f"{times[-1]:.6f}"
    )

    print(
        f"Final minimum / maximum: "
        f"{minimum_values[-1]:.6f}, "
        f"{maximum_values[-1]:.6f}"
    )

    print(
        f"Final quadratic energy: "
        f"{quadratic_values[-1]:.10e}"
    )

    print(
        f"Final Lyapunov energy: "
        f"{lyapunov_values[-1]:.10e}"
    )

    print(
        "Final solution saved to "
        f"{DATA_DIR / 'final_solution.csv'}"
    )


if __name__ == "__main__":
    main()